SNOWFLAKE_USER = "SANJANAJHA"
SNOWFLAKE_PASSWORD = "Stronger@29081997"
SNOWFLAKE_ACCOUNT = "BT86214.LL20960"  # e.g. xy12345.ap-south-1
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
SNOWFLAKE_DATABASE = "SNOWFLAKE_LEARNING_DB"
SNOWFLAKE_SCHEMA = "INFORMATION_SCHEMA"
